### ISSUE TITLE
Couldn't include file 'includes\modules\fluffydiscord.lua' (File not found) (@lua/autorun/client/discord-rpc.lua (line 4))

### ISSUE THREAD

**Issue by maxverwiebe** [fluffy-servers/gmod-discord-rpc#1]
Hey, I have installed and configured everything like the README says. But on the server I get the error:

Couldn't include file 'includes\modules\fluffydiscord.lua' (File not found) (@lua/autorun/client/discord-rpc.lua (line 4))

[ERROR] lua/autorun/client/discord-rpc.lua:4: Module not found!
  1. require - [C]:-1
   2. unknown - lua/autorun/client/discord-rpc.lua:4

**Comment by rafraser** [comment]
This was related to running the game on the 64 bit branch - I've built a 64 bit version of the .dll, which can be found on the Releases page if needed.
