### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by logan2611** [fluffy-servers/gmod-discord-rpc#10]
Under the current license (or lack thereof) no one is technically allowed to fork, modify or redistribute it.

**Comment by rafraser** [comment]
I'm not really emotionally invested in this - is the MIT license fine?

**Comment by logan2611** [comment]
Personally I think MIT is great. If you want to see what the various licenses allow for in an easy to read format, I suggest https://tldrlegal.com

**Comment by rafraser** [comment]
I've gone ahead and added the MIT licence, which should be good enough for anyone that wants to use this.

Since this is just a small gmod project and nothing too serious I'm not going to bother adding a code of conduct or issue templates etc.

**Comment by thexkey** [comment]
can we use GPL v3 on our fork that me and @logan2611 work on? (https://github.com/pootis-network/gmod-discord-rpc)

**Comment by rafraser** [comment]
sure thing
