### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by asupreme1337** [fluffy-servers/gmod-discord-rpc#11]
`[discord] addons/discord/lua/autorun/client/cl_discord.lua:52: attempt to call global 'DiscordUpdateRPC' (a nil value)
  1. DiscordUpdate - addons/discord/lua/autorun/client/cl_discord.lua:52
   2. fn - addons/discord/lua/autorun/client/cl_discord.lua:58
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:109`

The **.dll** module is located in lua/bin. I hope this error can be corrected

**Comment by rafraser** [comment]
It looks like the dll module isn't installed correctly - but it should stop if the module isn't detected.

Couple of quick questions to help diagnose:
 - Have you installed the module on the **client**?
 - What OS are you running, and what version of the dll have you installed?

(if you're running MacOS, this module currently doesn't support that but I can look into it for you)

**Comment by asupreme1337** [comment]
• Yes, the dll module is installed.
• I use OC Windows 10, the version of the dll module is x64.

**Comment by rafraser** [comment]
Are you running the 64bit beta branch?

**Comment by asupreme1337** [comment]
Yes

**Comment by rafraser** [comment]
No other errors in console when the game starts?

If nothing else, try also installing the 32bit version of the module just in case you're accidentally running the 32bit version of the game

**Comment by Kesefon** [comment]
Are you using the .dll from the release page?
If so, please try the .dlls from [GitHub Actions](https://github.com/fluffy-servers/gmod-discord-rpc/actions/runs/760452205).

**Comment by asupreme1337** [comment]
There are no more errors in the console, except for the one indicated above.

I will try the dll modules from Kesefon and write here if any errors occur.

**UPD:** Now everything is working. Thank you, I will test further!

![image](https://user-images.githubusercontent.com/72765777/118697161-acee7780-b817-11eb-9f9e-8dc1df6654f0.png)

**Comment by rafraser** [comment]
Glad that this all worked out! I'll update the release modules soon.

**Comment by rafraser** [comment]
I've made a new release with the latest DLL versions https://github.com/fluffy-servers/gmod-discord-rpc/releases/tag/1.1
