### ISSUE TITLE
Better console messages if module is missing

### ISSUE THREAD

**Issue by rafraser** [fluffy-servers/gmod-discord-rpc#18]
At current, there is some basic handling Lua side where the addon bails out if the module isn't installed at all.

```
if file.Find("lua/bin/gmcl_gdiscord_*.dll", "GAME")[1] == nil then return end
```

I just accidentally launched 64bit Garry's Mod with the 32bit version of this module installed, and there were a couple Lua errors. Woops!

There's a couple of improvements I think we can make to this:

- Check for the specific .dll file for the appropriate version of the game. This would stop errors if someone installs the wrong version!
- If the module isn't found at all, maybe we could display a console message saying something like "This server supports Discord Rich Presence - if you're interested, install the module"

If anyone has thoughts on this sort of stuff, let me know.

**Comment by FlorianLeChat** [comment]
This check could just be replaced by using [util.IsBinaryModuleInstalled](https://wiki.facepunch.com/gmod/util.IsBinaryModuleInstalled) which has recently been added to Garry's Mod to properly verify whether a binary module is installed on the game and supports all branches/environments:

```lua
if not util.IsBinaryModuleInstalled("gdiscord") then return end
```

**Comment by rafraser** [comment]
Wow, that's super convenient! I haven't kept up to date with the latest Lua additions so thanks for telling me about that
