### ISSUE TITLE
buttonPrimaryLabel and buttonPrimaryUrl is broken

### ISSUE THREAD

**Issue by SasnyParen** [fluffy-servers/gmod-discord-rpc#19]
buttonPrimaryLabel and buttonPrimaryUrl does not work on gmcl_gdiscord_win64.dll

**Comment by rafraser** [comment]
This was fixed in #17 and I forgot to create a new release for it - sorry about that.

If you update your binary module to use release 1.2.1 (https://github.com/fluffy-servers/gmod-discord-rpc/releases/tag/1.2.1) the issues should be resolved.
